CREATE TABLE normalized_security_events (
    event_uid TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    source_event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT,
    severity TEXT NOT NULL,
    severity_rank INTEGER NOT NULL,
    status TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    ingested_at TEXT NOT NULL,
    asset_hostname TEXT,
    asset_ip TEXT,
    asset_criticality TEXT,
    user_name TEXT,
    tactic TEXT,
    technique TEXT,
    raw_confidence TEXT,
    dedupe_key TEXT NOT NULL UNIQUE,
    tags_json TEXT NOT NULL,
    enrichment_notes_json TEXT NOT NULL,
    raw_json TEXT NOT NULL
);
